#!/usr/bin/env python3
"""Generate Sources/EeveeSpotify/Flags/EeveeFlagCatalog+Generated.swift
from the newest Symbols/baseline-*.txt symbol dump.

Kept in sync with the binary-diff workflow: after refreshing a baseline
(refresh_baseline=true -> merge the diff-baseline-* branch), re-run:

    python3 Scripts/generate-flag-catalog.py

The generated file is committed, so builds never depend on having an IPA or
the Symbols/ directory around.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYMBOLS = ROOT / "Symbols"
OUT = ROOT / "Sources/EeveeSpotify/Flags/EeveeFlagCatalog+Generated.swift"

HEADER = """\
// GENERATED by Scripts/generate-flag-catalog.py from {source}.
// Do not edit by hand: re-run the generator after refreshing a baseline.
// Seeding source for the Flags explorer settings page.

import Foundation

enum EeveeFlagCatalog {{
    static let spotifyVersion = "{version}"
    static let generatedAt = "{generated_at}"
    static let all: [String] = [
{entries}
    ]
}}
"""


def newest_baseline() -> Path:
    baselines = sorted(SYMBOLS.glob("baseline-*.txt"))
    if not baselines:
        sys.exit("error: no Symbols/baseline-*.txt found")
    return baselines[-1]


def parse_version(path: Path) -> str:
    return path.stem.removeprefix("baseline-")


def extract_flags(path: Path) -> list[str]:
    flags: list[str] = []
    in_flags = False
    for line in path.read_text(errors="replace").splitlines():
        if line.startswith("["):
            in_flags = line.startswith("[flags]")
            continue
        if in_flags:
            name = line.strip()
            if name:
                flags.append(name)
    return sorted(set(flags))


def main() -> None:
    baseline = newest_baseline()
    version = parse_version(baseline)
    flags = extract_flags(baseline)
    if not flags:
        sys.exit(f"error: no [flags] entries in {baseline}")

    entries = "\n".join(f'        "{name}",' for name in flags)
    body = HEADER.format(
        source=baseline.name,
        version=version,
        generated_at=__import__("datetime").date.today().isoformat(),
        entries=entries,
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(flags)} flags, Spotify {version})")


if __name__ == "__main__":
    main()
